/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      borderRadius: {
        xs: '4px',
        sm: '8px',
        control: '12px',
        card: '16px',
        feature: '18px',
        navigation: '24px',
      },
      colors: {
        canvas: '#050505',
        surface: '#101010',
        'surface-raised': '#151515',
        'surface-overlay': '#1A1A1A',
        border: '#2A2A2A',
        'text-primary': '#F6F6F6',
        'text-secondary': '#A3A3A3',
        'text-tertiary': '#828282',
        'text-disabled': '#8A8A8A',
        lime: '#B8F500',
        'on-lime': '#050505',
        'lime-surface': '#101400',
        'lime-surface-strong': '#171C00',
        'lime-border': '#3A4B12',
        booking: '#A85DD4',
        'booking-strong': '#68289E',
        'booking-surface': '#302251',
        'on-booking': '#F6F6F6',
        success: '#B8F500',
        warning: '#F6C850',
        'warning-surface': '#2B2100',
        danger: '#FF6B6B',
        'danger-surface': '#4A2020',
      },
      fontFamily: {
        sans: ['OpenSans-Regular'],
        'open-sans': ['OpenSans-Regular'],
        'open-sans-bold': ['OpenSans-Bold'],
      },
      fontSize: {
        display: ['34px', { fontWeight: '700', letterSpacing: '-0.6px', lineHeight: '40px' }],
        'screen-title': ['30px', { fontWeight: '700', letterSpacing: '-0.5px', lineHeight: '36px' }],
        'hero-title': ['26px', { fontWeight: '700', letterSpacing: '-0.4px', lineHeight: '32px' }],
        title: ['24px', { fontWeight: '700', letterSpacing: '-0.3px', lineHeight: '30px' }],
        'title-small': ['20px', { fontWeight: '700', letterSpacing: '-0.2px', lineHeight: '26px' }],
        section: ['17px', { fontWeight: '700', lineHeight: '23px' }],
        body: ['15px', { fontWeight: '400', lineHeight: '22px' }],
        'body-strong': ['15px', { fontWeight: '700', lineHeight: '22px' }],
        subhead: ['13px', { fontWeight: '400', lineHeight: '18px' }],
        'subhead-strong': ['13px', { fontWeight: '700', lineHeight: '18px' }],
        label: ['12px', { fontWeight: '700', letterSpacing: '0.4px', lineHeight: '16px' }],
        caption: ['11px', { fontWeight: '400', lineHeight: '15px' }],
        eyebrow: ['10px', { fontWeight: '700', letterSpacing: '1px', lineHeight: '14px' }],
        micro: ['10px', { fontWeight: '700', letterSpacing: '0.5px', lineHeight: '13px' }],
      },
      spacing: {
        hairline: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        screen: '18px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '48px',
        '4xl': '64px',
      },
    },
  },
  plugins: [],
};
